apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: votingapp
  name: jenkins-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]