apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: votingapp
  name: jenkins-rolebinding
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: votingapp
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
